export const CHOOSE_FILTER_DATA = 'CHOOSE-FILTER-DATA';
export const HANDLE_REFRESH_TIMER_CHANGE = 'HANDLE-REFRESH-TIMER-CHANGE';
export const HANDLE_ORDER_CHANGE = 'HANDLE-ORDER-CHANGE';
export const HANDLE_LANGUAGE_CHANGE = 'HANDLE-LANGUAGE-CHANGE';
export const HANDLE_FILTER_RESET = 'HANDLE-FILTER-RESET';
